module.exports = (dato, root) => {
  root.createDataFile('site.toml', 'toml', dato.site.toMap());

  root.directory('data', dir => {
    dato.singleInstanceItemTypes.forEach(itemType => {
      const item = dato.itemsOfType(itemType)[0];
      if (item) {
        root.createDataFile(`${itemType.apiKey}.toml`, 'toml', {
          id: dato.,
          active: dato.,
          brand_id: dato.,
          description: dato.,
          pdateadded: dato.,
          price: dato.,
          prod_weight: dato.,
          title: dato.,
          url: dato.,
          weight: dato.,
        });
      }
    });
    dato.collectionItemTypes.forEach(itemType => {
    color.logo: {name: dato.,cid: , images:},
    color.product: {name: dato.,cid: , images:}
    product_size: [dato.],
  });

  dato.collectionItemTypes.forEach(itemType => {
    root.directory(`content/_${itemType.apiKey}/`, dir => {
      dato.itemsOfType(itemType).forEach(item => {
        dir.createPost(`${item.autogeneratedSlug()}.md`, 'toml', { frontmatter: item.toMap() });
      });
    });
  });
};