module.exports = (dato, root) => {
  root.createDataFile('site.toml', 'toml', dato.site.toMap());

  root.directory('data', dir => {
    dato.singleInstanceItemTypes.forEach(itemType => {
      const item = dato.itemsOfType(itemType)[0];
      if (item) {
        root.createDataFile(`${itemType.apiKey}.toml`, 'toml', item.toMap());
      }
    });
  });

  dato.collectionItemTypes.forEach(itemType => {
    root.directory(`content/_${itemType.apiKey}/`, dir => {
      dato.itemsOfType(itemType).forEach(item => {
        dir.createPost(`${item.autogeneratedSlug()}.md`, 'toml', { frontmatter: item.toMap() });
      });
    });
  });
};