id = "124"
name = "Walkroyale"
locales = ["en"]
themeHue = 277
internalDomain = "walkroyale.admin.datocms.com"
noIndex = false
faviconMetaTags = [tagName = "meta"

[attributes]
name = "application-name"
content = "Walkroyale"

]